// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDELzvrIVxEdC5Uo4gzgTSRnxFHCF5Uz5E',
    appId: '1:36838862306:web:36cb1f52963907c8c15dbb',
    messagingSenderId: '36838862306',
    projectId: 'palevel-4dd6f',
    authDomain: 'palevel-4dd6f.firebaseapp.com',
    storageBucket: 'palevel-4dd6f.firebasestorage.app',
    measurementId: 'G-77RVZ43E78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCVHNkuQc47udMHlcWaukWz_7Nc1mC3EQ',
    appId: '1:36838862306:android:19536cc6958d45c0c15dbb',
    messagingSenderId: '36838862306',
    projectId: 'palevel-4dd6f',
    storageBucket: 'palevel-4dd6f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeu4onjrqzKYv_7k6JUbfpuAB6XsEKqwk',
    appId: '1:36838862306:ios:9e722afeb74807b8c15dbb',
    messagingSenderId: '36838862306',
    projectId: 'palevel-4dd6f',
    storageBucket: 'palevel-4dd6f.firebasestorage.app',
    iosBundleId: 'com.kernelsoft.palevel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeu4onjrqzKYv_7k6JUbfpuAB6XsEKqwk',
    appId: '1:36838862306:ios:65af23eed3c0ec27c15dbb',
    messagingSenderId: '36838862306',
    projectId: 'palevel-4dd6f',
    storageBucket: 'palevel-4dd6f.firebasestorage.app',
    iosBundleId: 'com.example.palevel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDELzvrIVxEdC5Uo4gzgTSRnxFHCF5Uz5E',
    appId: '1:36838862306:web:880457b605fb21b6c15dbb',
    messagingSenderId: '36838862306',
    projectId: 'palevel-4dd6f',
    authDomain: 'palevel-4dd6f.firebaseapp.com',
    storageBucket: 'palevel-4dd6f.firebasestorage.app',
    measurementId: 'G-ZY6JVNT5NZ',
  );
}
